- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: openstack
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  - debug:
      msg: "{{ openstack_info }}"

  - name: Wait until app will be up and running
    wait_for:
      host: "{{ item.public_v4 }}"
      port: 80
      delay: 10
    with_items:
      - "{{ openstack_info.ansible_facts.openstack_servers }}"

  - name: Check load balancer frontend servers
    uri:
     url: "http://{{item.public_v4}}"
     return_content: yes
     timeout: 800
    with_items:
      - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage
    tags:
      - osp.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
