---
- name: Install load balancer packages
  package:
    name: "{{ payload }}"
    state: present

- name: enable {{ payload }} at boot
  service:
    name: "{{ payload }}"
    enabled: yes

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart_haproxy

- name: start {{ payload }}
  service:
    name: "{{ payload }}"
    state: started

